### ISSUE TITLE
[Bug]: disabling inherit highlight css do not have any effect

### ISSUE THREAD

**Issue by hugomarins** [coldenate/flashcard-repetition-history#11]
### Contact Details

Discord: hugomarins

### Did you update to the latest plugin version?

- [X] Updated RemNote

### RemNote app version

1.15.7

### Plugin version

1.3.0

### What happened?

Trying to use custom colors is not working for me.

### Code of Conduct

- [X] I agree

**Comment by coldenate** [comment]
fixed in upcoming update.
