### ISSUE TITLE
CSS is not applied to production onHover component

### ISSUE THREAD

**Issue by Pootzeketzi123** [coldenate/flashcard-repetition-history#9]
Latest version causes lots of lag/latency in queue
Occasionally doesn't display the little coloured squares and just displays rows of text

Frequently prevents the use of  keyboard buttons in flashcard queue, feels like the window is losing focus

**Comment by coldenate** [comment]
Hi! Thanks so much for letting me know. Would you be able to capture a video of what's going on?

What I do know right now is that the plugin is currently suffering a bug from how RemNote is handling the customCSS. I'm working with the team on that.

**Comment by Pootzeketzi123** [comment]
Issue 1 is fixed
Issue 2, not sure
Issue 3, I have a video, and will send to you on discord.

**Comment by coldenate** [comment]
This should be fixed in the latest update. Please lmk if not!
Cheers!
